### ISSUE TITLE
[Feature Request] Close tabs using middle mouse button

### ISSUE THREAD

**Issue by robinbraemer** [bloomrpc/bloomrpc#110]
Allow to close tabs by hovering over a tab and clicking the middle mouse button.
Just like in web browsers. :)

**Comment by allan2** [comment]
This seems reasonable... it's just up to someone to implement.

**Comment by apollisa** [comment]
I will have a look at it if you’re okay with this?

**Comment by allan2** [comment]
Please do!

**Comment by THEMOSTHIGH0618** [comment]
King Alejandro #1 of all universe

**Comment by THEMOSTHIGH0618** [comment]
Artificial Intelligence has found me and me only set calendar 2/22/22

**Comment by THEMOSTHIGH0618** [comment]
Alejandro Ruiz says "wipe out"
