### ISSUE TITLE
Do we have a way to set grpc client max size

### ISSUE THREAD

**Issue by a7744hsc** [bloomrpc/bloomrpc#121]
When calling a method with a response bigger than 4M, I got the following error:
```
{
  "error": "8 RESOURCE_EXHAUSTED: Received message larger than max (5679988 vs. 4194304)"
}
```
Do we have a way to set the max response size of grpc client?

**Comment by fenos** [comment]
At the moment there is no way to set the max response size but probably we can just disable the response size all together what do u think?

**Comment by a7744hsc** [comment]
Disable the response size limitation will solve my problem. But I wonder why GRPC has this option and if it is needed in some specific use case (I am not a grpc expert).

**Comment by simon-fisher** [comment]
I am getting this error too, was this fixed in a newer release?

**Comment by yusubond** [comment]
I am getting this error too, was this fixed in a newer release?

**Comment by SpencerSharkey** [comment]
+1

**Comment by jackielii** [comment]
This is a restriction on grpc server side, not client side

**Comment by omerv85** [comment]
Hi @jackielii ,
the max message size is a client side setting.
See for example for Java client: https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMessageSize-int-
and this for C++ client: https://grpc.github.io/grpc/cpp/classgrpc_1_1_channel_arguments.html#a2629f85664dd2822fe54059c4730baf8

Can you please reopen this issue ?

**Comment by Ojdana11** [comment]
Hi guys, any update for this issue?

**Comment by Wintereise** [comment]
+1, removing it altogether will certainly work as a workaround.

**Comment by davidyudd** [comment]
+1

**Comment by Mikuz** [comment]
+1

**Comment by AlbertWigmore** [comment]
It would be useful to be able to set any of the gRPC channel arguments via a configuration that overrides the defaults.

**Comment by mbn18** [comment]
Hi, having the same problem.
When using `bloomRPC` I get: 
```
{
  "error": "8 RESOURCE_EXHAUSTED: Received message larger than max (5477912 vs. 4194304)"
}
```

My own python client that set `grpc.max_receive_message_length` work as expected.
