### ISSUE TITLE
How to make Bloomrpc work behind HTTP proxy (not https)?

### ISSUE THREAD

**Issue by yovannyr** [bloomrpc/bloomrpc#136]
I'm having trouble working with Bloomrpc behind a proxy at work.

When I have have the following environment variables:

http_proxy: http://domain\username:password@corp.com:8080
https_proxy: https://domain\username:password@corp.com:8080
no_proxy: localhost,127.0.0.1,0.0.0.0

**Comment by fenos** [comment]
@yovannyr sorry for the late reply, 

can you articulate the issue a bit more? why are you using an `http` proxy?

**Comment by yovannyr** [comment]
We use a http Proxy for any http request. The Proxy however is not needed for request inside our domain, so  bloomrcp need a configuration to ignore the proxy for internal Services or to use the proxy for external service. Thanks

**Comment by yovannyr** [comment]
I‘d like to contribute, but i am not so gut in js. Thanks

**Comment by posalex** [comment]
There is a workaround: just create an sh file like `start_bloom_without_proxy.sh` with following content:
`unset http_proxy`
`unset https_proxy`
`path/to/the/BloomRPC/AppImage`
So you can use BloomRPC with local addresses and if you need to access some addresses behind the proxy then start BloomRPC directly.

There is also an env variable `no_proxy`, but BloomRPC seems to ignore it.

**Comment by wairlex** [comment]
@posalex Thank you for your explanation. How can I apply this workaround in Windows?
