### ISSUE TITLE
Error While importing Proto(Maximum call  stack size exceeded)

### ISSUE THREAD

**Issue by AnkitaManuja** [bloomrpc/bloomrpc#163]
While Importing the Proto ,I am getting Maximun call stack size  issue.

**Comment by fenos** [comment]
Can you please share the protofile, I think it might related to this #69

**Comment by DuriDuri** [comment]
+ 1

**Comment by anshulprakash** [comment]
I am having a similar issue with the below protofile:
`
/**
 * Version 1alpha2
*/
syntax = "proto3";

package test.v1alpha2;

service test {
    rpc Test(TestRequest) returns (TestResponse) {}
}
message TestRequest {
    string test = 1;
}

message TestResponse {
   string test = 1;
}
`
I think it is an issue with the package name as when I name the package as test instead test.v1alpha2 it works fine.

**Comment by BitKaitsu** [comment]
I've managed to get this with the following:

I have a directory called `Foo` with two subdirectories `Bar` and `Baz`.

`Baz` contains a proto file called `baz.proto` with these contents:
```
syntax = "proto3";

package Test.Foo.Baz;

message Foobar {
    int32 foo = 1;
}
```

`Bar` also contains a single proto called `bar.proto` with these contents:
```
syntax = "proto3";

import "Foo/Baz/baz.proto";
package Test.Foo.Bar;

service Foo {
    rpc Foobar(FoobarRequest)
    returns (FoobarResponse) {}
}

message FoobarRequest {
}

message FoobarResponse {
    Test.Foo.Baz.Foobar foobar = 1;
}
```

It works as expected if I change the service name to something else, e.g., `Foo2` or if I change `Foo` in the package name for both protos to something else.

**Comment by gabschne** [comment]
This error happens when the proto file defines a service whose name is equal to the very first part of the package path:
```
syntax = "proto3";

package foo.bar;

service foo {}

// => error
```
Note that the package path must consist of at least two parts, otherwise it works again:
```
syntax = "proto3";

package foo;

service foo {}

// => works
```
It's also case-sensitive:
```
syntax = "proto3";

package foo;

service Foo {} 

// => works
```
Unfortunately I do not have enough time to look into it, but I hope that this will help someone to solve the problem.

**Comment by BitKaitsu** [comment]
> This error happens when the proto file defines a service whose name is equal to the very first part of the package path:

This is not true as the error happens in my example where the service's name matches the second part of the package path. Seems more like the service's name cannot match any part of package path if the path has multiple parts.

**Comment by gabschne** [comment]
@BitKaitsu 

> This is not true

How can you know what's "true" for me?

The error definetly doesn't happen **for me** with the example I provided where the name is not the first part.

Which version do you use?

**Comment by BitKaitsu** [comment]
> 
> Which version do you use?

I'm using the latest version (1.4.1).

> How can you know what's "true" for me?

Because my example contradicts yours.

> The error definetly doesn't happen **for me** with the example I provided where the name is not the first part.

While it's true that in your examples the behaviour is correct when the service is named `bar` and incorrect when it's named `foo`, it also doesn't work with `foo` if you add things before `foo` in the package path. So it is not limited to just matching the first part of the package path.

When using the last part of the path as the service name, it works every time, but leads to an error when using any other part of the path.
```
syntax = "proto3";

package a.b.foo.bar;

service bar {}

// => works
```

----
```
syntax = "proto3";

package a.b.foo.bar;

service foo {}

// => error
```

----
```
syntax = "proto3";

package a.b.foo.bar;

service b {}

// => error
```

----
```
syntax = "proto3";

package a.b.foo.bar;

service a {}

// => error
```

**Comment by gabschne** [comment]
In fact, seems like I didn't test it with more than 2 parts, which explains my wrong conclusion. I've updated my comment from earlier.

> Seems more like the service's name cannot match **any part** of package path if the path has multiple parts.

But then your comment is also not true as it works when the service name is equal to the last part of the path 😄:  

```
syntax = "proto3";

package a.b.foo.bar;

service bar {}

// => works
```

**Comment by BitKaitsu** [comment]
> But then your comment is also not true as it works when the service name is equal to the last part of the path 😄:

True, we both drew wrong conclusions 😄

**Comment by DenisBaturin** [comment]
```
syntax = "proto3";
package MyService.v1;

service MyService {}

// => error
```

The error occurs when I use the version suffix in the package name

**Comment by kblestarge** [comment]
Any update on this issue? I want to use this tool but this error is a blocker for me.

**Comment by Ma3oBblu** [comment]
+1
