### ISSUE TITLE
Unable to unzip the Zip or install exe it says unsafe

### ISSUE THREAD

**Issue by kishopriya** [bloomrpc/bloomrpc#164]
Unable to unzip the Zip or install exe it says unsafe

**Comment by shaneqld** [comment]
If running on Windows, right click on the executable > Properties > check Unblock > OK.

**Comment by slawo** [comment]
Similar issue on Mac OS the binary needs to be signed.

```“BloomRPC” cannot be opened because the developer cannot be verified.```

**Comment by Ahmad-Magdy** [comment]
@slawo 
Go to System preferences >> Security and privacy.
You will find the same message with "open anyway" button, click on it and you'll be able to open the app.
