### ISSUE TITLE
BloomRPC client sent grpc-bytes-type not parsed correctly by .NET Core 3.1 back-end. (All defaults)

### ISSUE THREAD

**Issue by Vinigas** [bloomrpc/bloomrpc#172]
First of all, I would like to say that I like this project.

Issue is then .NET Core 3.1 gRPC back-end service (created from official template with official dependencies and using everything in defaults) receives RPC correctly, but then parses the ByteString it's length is always 0 no matter what "data" was specified by BloomRPC.

Editor generated request body (defaults):
```json
{
  "uuidBytes": {
    "type": "Buffer",
    "data": [
      72,
      101,
      108,
      108,
      111
    ]
  }
}
```

Proto3:
```proto3
syntax = "proto3";

option csharp_namespace = "GrpcService1";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  bytes uuidBytes = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```

![image](https://user-images.githubusercontent.com/6695244/73926887-15426f80-48d9-11ea-8d1e-30acf433dcd1.png)

![image](https://user-images.githubusercontent.com/6695244/73926942-30ad7a80-48d9-11ea-933e-7949cf5d3690.png)

![image](https://user-images.githubusercontent.com/6695244/73927026-533f9380-48d9-11ea-9b53-c150f3691619.png)

**Comment by Vinigas** [comment]
Added server-side project to back up the issue: https://github.com/Vinigas/bug-report--uw-labs--bloomrpc--issue-172
You can run it with [Docker](https://docs.docker.com/install/) using _docker-build.sh and _docker-run.sh (publishes 81 port) scripts inside repo.

**Comment by fenos** [comment]
This is related to #101

**Comment by fenos** [comment]
@Vinigas thanks for the repo! I'll have a play with it!

**Comment by Vinigas** [comment]
[OFF-TOPIC] More use-ready examples covering common gRPC use-cases can be found at: https://github.com/grpc/grpc-dotnet/tree/master/examples
