### ISSUE TITLE
Ctrl+enter sends an empty message when making a request

### ISSUE THREAD

**Issue by deitrix** [bloomrpc/bloomrpc#173]
The new ctrl+enter functionality is a welcome addition, however it doesn't seem to be working on Linux/MacOS. I'm unsure of other platforms.

Pressing ctrl+enter does send the request, but appears to be sending an empty message. Pressing the play button works fine; the issue only occurs when pressing ctrl+enter.

The request was performed on a `gogo/protobuf` generated grpc server.

**Comment by fenos** [comment]
@deitrix thanks for reporting this, I will verify it and fix it for the next release

**Comment by buehler** [comment]
@fenos I can confirm it :-)

![image](https://user-images.githubusercontent.com/1067213/74323172-693fcf00-4d85-11ea-9626-6b97bfa0b04c.png)

**Comment by adzimzf** [comment]
I have same experience on this issue
