### ISSUE TITLE
TLS setting is not remembered despite same url.

### ISSUE THREAD

**Issue by buehler** [bloomrpc/bloomrpc#175]
Hey there

I really love the application, but one thing that annoys me right now is when using secure (TLS) connections with a server certificate and the creating a new tab by clicking on the next method, the TLS setting is reset to root certificate and "unsecure". Even if the url did not change.

Regards :)

**Comment by buehler** [comment]
I just tested with 1.4.1
The same problem does not exist anymore (with the environments) but when opening a new tab, the environment gets reset every time :-)

**Comment by fenos** [comment]
@buehler thanks for your feedback! 

Ok! I agree on keeping the environment set when you open new tabs

**Comment by fenos** [comment]
@buehler the only problem i'm foreseeing is that, what if you have 3 tabs with all different environments? 

We should probably look at the latest active tab and copy the configuration to the new tab, thoughts on this?

**Comment by yuraxdrumz** [comment]
@buehler @fenos Hey. Maybe it will be better to keep an environment per protofile. That way the tabs will always be consistent. Maybe inherit protofile name when loading a tab and load environment based on that. Any thoughts?

**Comment by buehler** [comment]
hmm @yuraxdrumz it's an idea, but ux wise I'd guess it would be too much "magic". I think just use the latest active tabs environment would be a clear state..

@fenos: So when using two tabs with two different urls / environments, just open the new one with the url / environment / setup that the last active one used.

What do you think?

**Comment by yuraxdrumz** [comment]
From what it looks like, the current structure is:
- BloomRPC
  - TabList
    - Tab <- tab state is kept here
      - Editor <- state is kept here
        - Options <- tls selected state is kept here and injected from tab
          - TLSManager

Maybe we can keep a top level variable and inject its setter as props, so that when latest tab changes certificate, it will get automatically updated. Everything else will be injected as usual. A new tab will receive either last tls certificate as props or the initial. 
- BloomRPC <- general state + lastTLS
  - TabList
    - Tab <- tab state is kept here, new tab is either lastTLS or initial like before
      - Editor <- state is kept here
        - Options <- tls selected state is kept here and injected from tab
          - TLSManager

Either way it must be outside the scope of tab, as its higher level state.
What do you think?
