### ISSUE TITLE
 google.protobuf.ListValue not supported

### ISSUE THREAD

**Issue by picaso** [bloomrpc/bloomrpc#176]
Hi!

Tried loading a proto file with a field of type  `google.protobuf.ListValue`  imported from `import "google/protobuf/struct.proto";
` but it throws an error on the client - 
```javascript
{
  "error": "Error parsing the request message, please report the problem sharing the offending protofile"
}
```
Getting rid of the offending field and everything is back to normal.

**Comment by fenos** [comment]
@picaso thanks for reporting this, i'll have a look

**Comment by fenos** [comment]
could please share the protofile
