### ISSUE TITLE
Support TLS Passphrase

### ISSUE THREAD

**Issue by yuraxdrumz** [bloomrpc/bloomrpc#177]
Current TLS solution does not accept a passpharse.
the issues here: https://github.com/grpc/grpc-node/issues/413 and https://github.com/grpc/grpc-node/pull/416 suggest that there is an open PR for this feature which will make it to grpc-js. This would be very useful as all my companie's services use grpc over mutual tls and currently I have to manually comment out the tls to make everything work.

Currently the `createSsl` looks like this:
```js
creds = credentials.createSsl(
    fs.readFileSync(this.tlsCertificate.rootCert.filePath),
    this.tlsCertificate.privateKey && fs.readFileSync(this.tlsCertificate.privateKey.filePath),
    this.tlsCertificate.certChain && fs.readFileSync(this.tlsCertificate.certChain.filePath),
);
```

Instead, until a proper fix is merged, I suggest something like this:
```js
const privateKey = execSync('openssl ec -in key.pem -passin "pass:your-pass"')
creds = credentials.createSsl(
    fs.readFileSync(this.tlsCertificate.rootCert.filePath),
    privateKey,
    this.tlsCertificate.certChain && fs.readFileSync(this.tlsCertificate.certChain.filePath),
);
```

I know this is ugly but at least we could work with passpharse pem keys directly. Maybe make an interface and hide calling the `createSsl` behind an abstraction, so that when a proper fix is merged to the official grpc repo we can simply change it.

EDIT: 
tried passing the private key like what I suggested and I seem to be getting this error:
`E0212 02:42:00.460109000 4599233984 ssl_transport_security.cc:1245]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000006b:SSL routines:OPENSSL_internal:BAD_ECC_CERT.`
I checked how the certificate gets decoded with the EC + passphrase on my golang grpc client and I get the same key output as in Node.js. Strange

**Comment by fenos** [comment]
@yuraxdrumz Hi, thanks for reporting the issue,

Before we make some change let's first make it work with the "hack" that you are suggesting,

If i was you, i would try to hard code the `unencrypted` private certificate and see if that work, maybe the output of the  `execSync` is not normalised at it should.

Once you make it work that way we can start looking at some node-js libraries that handles `openssl` calls like:

https://github.com/lspiehler/node-openssl-cer or any other popular one. Once we get things working locally, I'll be happy to support this in the UI

**Comment by yuraxdrumz** [comment]
Found an issue that has a similar problem to mine, golang client works and node.js doesnt. https://github.com/grpc/grpc-node/issues/157
Looks like it has not been resolved as well.

**Comment by fenos** [comment]
@yuraxdrumz i have the feeling that we can make it work. I'll have a play over the weekend

**Comment by yuraxdrumz** [comment]
Any progress on this?
