### ISSUE TITLE
feature: enable electron auto update

### ISSUE THREAD

**Issue by buehler** [bloomrpc/bloomrpc#178]
It would be nice to have the app update itself with electron autoupdater :-)

`electron-updater` is what I have used before.

Or is it updating and I messed up?

**Comment by fenos** [comment]
This sounds like an awesome thing to have, although it might be slightly more difficult for `BloomRPC` since it has the `gRPC` binary embedded into the app.

I'll have a look what we can do about this, although is a bit low priority than other features

**Comment by buehler** [comment]
No worries :-) If I got time, I may can look into it.
