### ISSUE TITLE
14 UNAVAILABLE: DNS resolution failed

### ISSUE THREAD

**Issue by bcba25** [bloomrpc/bloomrpc#184]
Hello. I can't get any response no matter what I put under address and port. Only getting **14 UNAVAILABLE: DNS resolution failed** as response. I've tried localhost:50053, 127.0.0.1, 0.0.0.0, I don't have any prefixes in front of address. Nothing is working, except my own written client which is connecting and calling server without any issues. Any suggestions ? Using latest version 1.4.1 on Mac

**Comment by bcba25** [comment]
Ping

**Comment by barlen** [comment]
similar problem, but localhost works. another site I am testing gives this error. can look it up in terminal just fine. App v1.4.1.145 on macOS 10.15.4.

**Comment by viktor-nikolaev** [comment]
same problem

**Comment by Jacksliwen** [comment]
same problem, using windows,version1.4.1

**Comment by lcb1208** [comment]
same problem, using windows,version1.4.1

**Comment by Amos-Pan-lei** [comment]
same problem ,whatever i set the ip address,  just get 

{
  "error": "14 UNAVAILABLE: DNS resolution failed"
}

i try to add Certification to make it work ,but .
my pc  donnot has any persional  useable Certification .
so ,i failed again

**Comment by jackielii** [comment]
Can you paste a screenshot here?

**Comment by nicksnz3k** [comment]
i has the same error

**Comment by tndata** [comment]
I have the same error

**Comment by matt-psaltis** [comment]
Are people including a Scheme (https://) on the front of your host name? That can cause this error - I note the OP mentioned they didn't not sure if everyone caught that since. Also read dns:/// can help in some situations.

**Comment by nkasozi** [comment]
Ok...Spent a lot of time on this simple issue. I really think the problem is the UI isn't as intuitive to some people. to get rid of this error I had to click this button (Which is grey and has GRPC written on it => I assumed this enables or disables full on GRPC)
![image](https://user-images.githubusercontent.com/4717327/142996639-b946e00d-8ffd-4742-b8e7-d84d081e3b90.png)
![image](https://user-images.githubusercontent.com/4717327/142996734-07c37281-866f-4566-b796-239a5967295b.png)

**Comment by jackieli-tes** [comment]
Yes, when it's grey it means to use the vanilla GRPC binary protocol and address input should be the host + port, when it's toggled to "WEB" it uses GRPC-WEB protocol and it parses address as URL, so you can include the scheme, host, port and path.

I know it's confusing, improvement suggestions are welcom

**Comment by rajshanmugam-paysafe** [comment]
Replace uri with 0.0.0.0:<your port no>, say instead of http://localhost:5261 use 0.0.0.0:526

![DNS resolution failed](https://user-images.githubusercontent.com/73795570/148998253-84a837a5-cdb2-4e2a-bd30-1fcb48fa969c.png)
1

**Comment by cutejaneii** [comment]
I'm having a gRPC service work over https, I set TLS, then it works. 
[](https://raw.githubusercontent.com/cutejaneii/temp/main/bloomRPC_issue.png)

**Comment by FaizUlHassan123** [comment]
i have add this url and its working 127.0.0.1:5005

<img width="1321" alt="Screen Shot 2022-01-21 at 12 47 06 PM" src="https://user-images.githubusercontent.com/37914870/150487168-a31d6366-9f54-4789-bbc1-8cc56593cc11.png">
1

**Comment by lextas** [comment]
I ran into this issue as well. Just leaving this here because people might overlook something as simple as removing the protocol and/or trailing slash.

```
http://localhost:1234    <-- 14 UNAVAILABLE: DNS resolution failed
http://localhost:1234/   <-- 14 UNAVAILABLE: DNS resolution failed
localhost:1234/             <-- 14 UNAVAILABLE: DNS resolution failed

localhost:1234              <-- works
0.0.0.0:1234                  <-- works
127.0.0.1:1234              <-- works
```
Maybe parsing the URL and remove protocol and trailing slash in case the `gRPC `  toggle is true (so not `web`) should fix the majority of user issues.

**Comment by jackielii** [comment]
> Maybe parsing the URL and remove protocol and trailing slash in case the `gRPC ` toggle is true (so not `web`) should fix the majority of user issues (but I don't know if this breaks use-cases for people with proxy URLs).

Good point, I think this should be a very good pr.

The "address" box is interpreted differently in grpc vs grpc-web mode. In grpc mode, it's `host:port`, in grpc-web mode, it's just url where scheme and path can be omitted.

[grpc-web](https://github.dev/bloomrpc/bloomrpc/blob/f68cab9654690c07fce45dab2256c9f1d7e112e0/app/behaviour/sendRequest.ts#L381)

[grpc](https://github.com/bloomrpc/bloomrpc/blob/f68cab9654690c07fce45dab2256c9f1d7e112e0/app/behaviour/sendRequest.ts#L194)

grpc serviceClient construct is using the protobufjs's provided functionality. See [here](https://github.com/uw-labs/bloomrpc-mock/blob/19f37831ae65dec51bef8ccd41813687d5fef937/src/protobuf.ts#L14). It parses the proto files and constructs all the structs and methods. `service` is one of them. IIRC, grpc-web re-uses this part of the fucntionality
