### ISSUE TITLE
Sending request with google.protobuf.Struct

### ISSUE THREAD

**Issue by mikart143** [bloomrpc/bloomrpc#198]
So I am trying to send my request to server.
My protobuffer request consist of:
```
message HelloRequest {
   string name = 1;
   google.protobuf.Struct custom = 2;
}
```
and of course there is an import.

When I am trying to send 
```
{
  "name": "Worlddsssasda",
  "custom": {
    "object":{
      "name":"asdasdasdasdasdasdasd"
    }
  }
}
```

I am getting empty custom field. I do not know if that is correct or not.
I am working with rust and tonic. Sending custom object from rust client to server works fine

**Comment by hankish** [comment]
I'm having this issue as well.
