### ISSUE TITLE
bloomrpc can't parse response message has map<string, bool>

### ISSUE THREAD

**Issue by alonstar** [bloomrpc/bloomrpc#202]
I use 1.4.1 bloomrpc and got error "13 INTERNAL: Failed to parse server response".

I test it with C# client , it works. why can't  bloomrpc parse response?

```
message CheckConnectionResponse {
    map<string, bool> gateways = 1;
}

service ManagementService {
    rpc CheckConnections (google.protobuf.Empty) returns (CheckConnectionResponse);
}

```

**Comment by aaad** [comment]
I have the same problem.

**Comment by aclemmensen** [comment]
I see the same but with `map<string, int>`. It works in evans.

**Comment by gsmeets** [comment]
I'm experiencing similar issues with `map<string, string>`, but only when the value in the map is an empty string.

Interestingly, if I have two empty string values in the map, I get this result:

response:
```
{
  "foo": "", 
  "bar: ""
}
```

result:
```
{
  "foo": "bar"
}
```

**Comment by jackielii** [comment]
I think `map<string, Message>` is supported, will need to investigate

**Comment by animesh-sharama** [comment]
Any updates on this I am seeing the same issue with repeated field and Unicode strings?

**Comment by dilee** [comment]
I've got the same issue recently. Happened with a payload with repeated fields.

**Comment by EliasICerezo** [comment]
Another one here, it happens with map<string, Message>, the braces are not rendered, nor the semicolons on the json stuff
