### ISSUE TITLE
bloomrpc can't parse request which contains google.protobuf.Struct

### ISSUE THREAD

**Issue by shubhamgoyal49** [bloomrpc/bloomrpc#203]
I have a proto message as below:

```
message ProcessEventRequest {
  string Event = 1;
  google.protobuf.Struct Payload = 2;
}
```
and rpc as:

```
rpc ProcessEvent(ProcessEventRequest) returns (ProcessEventResponse) {}
```

Issue:
Whenever i am making the gRPC request through bloomrpc then the Payload is received as an EMPTY map[string]interface{} in golang.

I suppose this maybe request parsing issue and can be corrected using jsonpb library instead of JSON to parse/unmarshal the request.

**Comment by Sunfl4wer** [comment]
Here how I format my request
`"payload": {
    "fields": {
      "name": {
        "stringValue": "joe"
      },
      "age": {
        "numberValue": 28
      }
    }
  }`
More at: https://stackoverflow.com/questions/66574108/typescript-javascript-grpc-google-protobuf-struct-cannot-be-read
