### ISSUE TITLE
[FeatureRequest] Recursively import .proto files in a given folder

### ISSUE THREAD

**Issue by xbeta** [bloomrpc/bloomrpc#225]
Our use-case is centralize all of our proto files into a monorepo (just the .proto files). We currently have about 20+, but we would prefer that we just give a path of the directory, and Bloom can recursively import all the `.proto` files in that given path.

**Comment by dunyakirkali** [comment]
+1

**Comment by erawhctim** [comment]
Definitely a big pain point in using BloomRPC today.
