### ISSUE TITLE
[FeatureRequest] Auto-refresh

### ISSUE THREAD

**Issue by xbeta** [bloomrpc/bloomrpc#226]
Our current use-case, our `.proto` files are check in a monorepo with many other `.proto` files in a git repo.  We regularly update them, so sometimes we will forgot to update the new definitions after a new `git pull` and use it in Bloom. Can Bloom auto-refresh at startup?

**Comment by jackielii** [comment]
There is a refresh button, but auto refresh would be feature request

**Comment by xbeta** [comment]
@jackielii  Updated with only about auto-refresh
