### ISSUE TITLE
Poor Performance for Streaming Responses with Large Datasets

### ISSUE THREAD

**Issue by pnquest** [bloomrpc/bloomrpc#230]
I have an endpoint that can sometimes stream back hundreds of thousands of objects. Currently when I hit this from bloomRPC, it renders the first one or two and then hangs completely for much longer than it actually takes for the service to complete sending its responses. I typically just close it out after confirming that I start seeing responses.

I don't expect bloomRPC to be able to render them all as quickly as they come but it would be nice if:

1. It didn't become completely unresponsive in this scenario, forcing me to close the whole program rather than just hitting cancel
2. There was some kind of support for this scenario, for example let me specify a skip/take of the stream and only render that subset, or a count mode, where instead of rendering any of the responses, you just stream through them and display how many were received.

**Comment by NeverMorewd** [comment]
the same situation as me

**Comment by NeverMorewd** [comment]
I test the grpc-donet project.it hang on when i run the streamfrom server
![image](https://user-images.githubusercontent.com/10544200/134310121-6b65662d-08f5-465e-8e85-35748e33a7c2.png)

**Comment by NeverMorewd** [comment]
![image](https://user-images.githubusercontent.com/10544200/134311676-5b07a20e-39b8-4fa8-88cb-48e6b4dd63b1.png)
