### ISSUE TITLE
No pre-request script or interceptor

### ISSUE THREAD

**Issue by sangianpatrick** [bloomrpc/bloomrpc#231]
maybe could be considered to add pre-request script or maybe some client interceptor (no problem if it written in js).

**Comment by jackielii** [comment]
I'm not sure what's the purpose of this?

**Comment by sangianpatrick** [comment]
Hei @jackielii , I was wondering if this app has the same feature of Postman had. Then it'd be easy to run an integration test via this app. Let say we need to pass an encrypted value to the password field, then we have to encrypt that outside the application (in another one), but we do not do that efforts if it has pre-request script (like Postman does) we can just write a custom in-app encryption function to encrypt the plain text value we want to put. Hope this could fulfilled your question.
