### ISSUE TITLE
Installation on MacOS with homebrew is not executable because "developer cannot be verified"

### ISSUE THREAD

**Issue by sarndt** [bloomrpc/bloomrpc#233]
Hey,

not sure if this is the right place to report this issue, but the brew formular linked back to this git project, so I hope I'm correct here.

Installing bloomrpc via `brew cask install bloomrpc` and then trying to open it was met on my system with the following error message:

`“BloomRPC” cannot be opened because the developer cannot be verified.`
`macOS cannot verify that this app is free from malware.`

![Screenshot 2020-07-27 at 15 03 52](https://user-images.githubusercontent.com/570548/88545735-aa6a2980-d01b-11ea-9486-67ec3ca38fc3.png)

Looks like a code-signing issue to me.

My System: 

MacOS Catalina 10.15.6
Homebrew was updated before installation was tried.
`brew cask info bloomrpc` says:

```shell
bloomrpc: 1.4.1
https://github.com/uw-labs/bloomrpc
/usr/local/Caskroom/bloomrpc/1.4.1 (122B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/bloomrpc.rb
==> Name
BloomRPC
==> Artifacts
BloomRPC.app (App)
```

**Comment by dvdplm** [comment]
Same here.

**Comment by dvdplm** [comment]
…and FWIW the same happens when downloading the `.zip` from the releases page (so doesn't seem to be a homebrew issue).

**Comment by sarndt** [comment]
Is there anyone still working on this project actually? No responses to most issues seem to say that this project has been abandoned.

**Comment by GlebIgnatevEmlid** [comment]
+1, it seems like the latest .dmg is not signed or whatever.

**Comment by abbottm-go** [comment]
You can change this in your privacy settings, to individually over-write the preferences. 

try and open the app 

go to settings, privacy, click the pad lock and then you should see an option to open this application.

**Comment by sarndt** [comment]
> You can change this in your privacy settings, to individually over-write the preferences. 
> 
> try and open the app 
> 
> go to settings, privacy, click the pad lock and then you should see an option to open this application.

Sorry but that isn't really a great solution. I'm not a fan of adding security exceptions when this could be solved by properly signing the software. 
Now I don't know if signing it is associated with any cost, and I can understand if the developer would not want top incur a cost should that be the case, but pretty much every other software that I use via brew doesn't have this problem. 

If it can't be solved "properly" I guess thats my loss then.

**Comment by abbottm-go** [comment]
> > You can change this in your privacy settings, to individually over-write the preferences.
> > try and open the app
> > go to settings, privacy, click the pad lock and then you should see an option to open this application.
> 
> Sorry but that isn't really a great solution. I'm not a fan of adding security exceptions when this could be solved by properly signing the software.
> Now I don't know if signing it is associated with any cost, and I can understand if the developer would not want top incur a cost should that be the case, but pretty much every other software that I use via brew doesn't have this problem.
> 
> If it can't be solved "properly" I guess thats my loss then.

I don't work on the project. I was merely providing a work around, should your situation absolutely require a solution like bloomRPC.

**Comment by mjroeleveld** [comment]
Disable Gatekeeper: https://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/

**Comment by sarndt** [comment]
> Disable Gatekeeper: https://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/

If you had read the discussion above, you would have seen that this is a workaround that at least for me is not a „fix“ for this issue.

**Comment by jasonclg** [comment]
Any update on this issue?

**Comment by EdmundsEcho** [comment]
This seems to be an ongoing issue.  While I greatly appreciate having access to this free resource (I know it takes a lot of work), is there not a way to at least get it so we can add the app to the list of permissions to access the drive (or whatever is required).  

Surely a shared experience for something like this is to get a  link to the system preferences, not a message that only offers "trash | cancel".  Also, I cannot seem to add the app to anything other than disk.  The system still denies access.
