### ISSUE TITLE
 "Error constructing the request. e is not a constructor"

### ISSUE THREAD

**Issue by leofj** [bloomrpc/bloomrpc#238]
I'm getting this weird error on some services. I couldn't figure it out when it happens. For some services it doesn't happen and for some it always happens.
It's before even calling the service, so I don't think it's related to the service itself.
I tried different installations and also building from source, always the same problem.
I'm using Manjaro.

![Screenshot from 2020-08-11 10-09-11](https://user-images.githubusercontent.com/64426216/89873529-e0caab80-dbba-11ea-934b-8bc39bcd077a.png)

**Comment by marioarranzr** [comment]
I have the same issue. No matter the proto or the body, it doesn't even make the request

**Comment by leofj** [comment]
I found a workaround using a service that works. I copied the service that doesn't show the error, change the content of the proto file to the one I wanted and then copied the rest of the code.
Not a good process, but at least it was a way to test my service.
That also shows that this error seems very random

**Comment by devavrath-doordash** [comment]
I'm seeing this issue too. It happens for protos with field masks.
Bloom works perfectly on my colleague's machine and we are on the same bloom version [1.4.1 (1.4.1.145)].
Is this a recent issue?

**Comment by avdept** [comment]
Having same issue

**Comment by pcriadoperez** [comment]
Running into the same issue to

**Comment by jackielii** [comment]
can you try latest release and also share minimal proto files to reproduce?

**Comment by teros0** [comment]
Same error, latest version.
Proto file [example](https://pastebin.com/XQz2Bs6E).

**Comment by jackielii** [comment]
I'm unable to reproduce this error, can you please open the developer tools via "View" -> "Toggle Developer Tools" and paste a screenshot of the error stack?

**Comment by teros0** [comment]
![image](https://user-images.githubusercontent.com/23041111/98835813-8e16bf00-2449-11eb-8bb3-3fe9b9ff63fd.png)

**Comment by jackielii** [comment]
Thanks for the screenshot, I believe the error happened on https://github.com/uw-labs/bloomrpc/blob/master/app/behaviour/sendRequest.ts#L58, it might have returned an empty?

is every proto file failing or just this one?

**Comment by teros0** [comment]
Not every but most of them.

**Comment by teros0** [comment]
@jackielii are there any updates on this?

**Comment by jackielii** [comment]
@teros0 sorry was on holiday, had lots of work stuff have to deal with.

the biggest problem for me is I'm unable to produce this.

**Comment by devavrath-doordash** [comment]
is this tied to an angular version or some other dependency?

**Comment by arturhayne** [comment]
I had same issue that was solved after clean up my "Import Paths". Before,  I had added not only my packages folder, but some services path that was a problem. When I took off the services folder from "Import Paths" it worked.

**Comment by Bhala1987** [comment]
I kept on getting the following errors in BloomRPC tool:
1. Error constructing the request e is not a constructor (OR)
2. e[this.protoInfo.methodName] is not a function
I have tried the following options and none worked:
1. BloomRPC tool upgrade from 1.4.1 to 1.5.2
2. protoc --version from 3.11.4 to 3.14.0
Finally worked by just removing the path from 'Import Paths' :)

**Comment by teros0** [comment]
Yes, worked for me as well.
Thanks guys.

**Comment by avdept** [comment]
Any progress on this? Keep getting these errors for random proto files.

**Comment by cgthayer** [comment]
Seeing this also

**Comment by fleytman** [comment]
The problem is still relevant

**Comment by claireyuan21** [comment]
I'm seeing the same issue 
<img width="1051" alt="Screen Shot 2022-09-19 at 6 50 21 PM" src="https://user-images.githubusercontent.com/89038795/191323203-62d4dafc-7ee0-462d-ae20-e323574c55ff.png">
