### ISSUE TITLE
Failed to receive the preface from client

### ISSUE THREAD

**Issue by R4zorSharp** [bloomrpc/bloomrpc#240]
I'm getting the above error in the server log whenever I try to send a request from the BloomRPC client. For the life of me I cannot find how to make a client send a preface. Can someone please assist ?

**Comment by jackielii** [comment]
needs more info here. what's a "preface"

**Comment by ggirtsou** [comment]
@R4zorSharp could this error be because your gRPC server runs without TLS but the request is proxied to your service without SSL termination?
