### ISSUE TITLE
brew error while installation

### ISSUE THREAD

**Issue by softmarshmallow** [bloomrpc/bloomrpc#241]
when running, `brew cask install bloomrpc`
>Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/bloomrpc

**Comment by jackielii** [comment]
will investigate, but are you able to install using the dmg file?

**Comment by softmarshmallow** [comment]
Yup.

**Comment by bernardo-martinez** [comment]
I'm having the same problem on macOS Catalina 10.15.7.
