### ISSUE TITLE
Unable to Load Protobuf File with Field Options

### ISSUE THREAD

**Issue by borchero** [bloomrpc/bloomrpc#243]
I currently have a Protobuf file similar to the following to validate input in Go:

```protobuf
syntax = "proto3";
package rpc;
option go_package = "go.example.com/rpc";
import "validate/validate.proto";

service Service {
    rpc Do(DoRequest) returns (DoResponse);
}

message DoRequest {
    string name = 1 [(validate.rules).string.pattern = "^[a-z]+$"];
}

message DoResponse {}
```

However, when I try loading the definition, I get the following error:

```
illegal value '[' (/Users/username/test.proto, line 11)
```

Although BloomRPC can easily ignore these options, it would be nice to still be able to use definitions like these without manually removing the options.

- BloomRPC version: 1.4.1

**Comment by jackielii** [comment]
can you please try latest release?

**Comment by cetanu** [comment]
I'm running version 1.5.2 and have a similar problem

**Comment by darewreck54** [comment]
I'm running into the same issue.  How do you ignore these errors?  Mine just won't load the proto at all because of the errors

**Comment by borchero** [comment]
My solution was to move to https://github.com/fullstorydev/grpcui 🙃
