### ISSUE TITLE
Bug option allow_alias = true

### ISSUE THREAD

**Issue by wdfinch** [bloomrpc/bloomrpc#244]
If the photo contains option allow_alias = true in an enum, Bloom will crash.

**Comment by jackielii** [comment]
can you provide minimal proto files to reproduce this?

**Comment by wdfinch** [comment]
In my case I think you just need an enum with the allow alias option. So for example:

```
enum MyEnum {
  OPTIONA = 0;
  OPTIONB = 1;
  OPTIONC = 1;
  OPTIOND = 2;
  option allow_alias = true;
}
```
