### ISSUE TITLE
google.protobuf.Value field in Message causes error when loading protofile

### ISSUE THREAD

**Issue by jsrolon** [bloomrpc/bloomrpc#249]
Hi, I'm currently on version `1.4.1`, running on Ubuntu. I have the following simple protofile that uses `google.protobuf.Value` as a field in a grpc message:

```protobuf
syntax = "proto3";
  
package offending.proto;

import "google/protobuf/struct.proto";

service OffendingService {
  rpc Rpc (OffendingMessage) returns (OffendingMessage) {
  }
}

message OffendingMessage {
    google.protobuf.Value session = 1;
}
```

When loading this protofile I get the following error in BloomRPC:

```json
{
  "error": "Error parsing the request message, please report the problem sharing the offending protofile"
}
```

What's interesting is that having this `google.protobuf.Value` inside a map, as in `map<string, google.protobuf.Value>` doesn't cause any issues and the file is parsed correctly by BloomRPC. I think this is definitely related to #176 .

**Comment by jackielii** [comment]
can you provide minimal proto files that reproduce this problem?
