### ISSUE TITLE
[FeatureRequest] Close multiple tabs

### ISSUE THREAD

**Issue by nate-anderson** [bloomrpc/bloomrpc#251]
It would be nice to have a menu item under 'Window', or a context menu option when right-clicking a tab, that would allow closing multiple tabs. 'Close all tabs' and 'Close other tabs' are common options in tabbed interfaces. Especially since tabs are variable width and can't be closed by rapidly clicking in the same place.

**Comment by JoeHartzell** [comment]
It seems that the keybind "CTRL+W" is bound for closing the current tab (command+w for OSX users). This might work as a work around for you. 

As a side note, I think being able to close tabs my scroll wheel clicking would be a good addition as well. Postman has a feature for this as well.

**Comment by jackielii** [comment]
would be a reasonable feature

**Comment by leonardo-k** [comment]
I use bloom a lot at work , and it's a great program...good job developers! 
however , a "close all tabs" feature is really needed , it would be a great improvement!
