### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by vusalalishov** [bloomrpc/bloomrpc#253]
It would be great to have support for environment variables like in Postman.

**Comment by jackielii** [comment]
this would be a nice feature, what's your primary use case? to set values in Metadata?

**Comment by DarinDev1000** [comment]
The use case I'd specifically be looking for is to be able to set `{ "Authorization": "Bearer <variable> }` in the request metadata.
Either a variable in the environment or even in the response of another call.
The same feature Insomnia currently has
