### ISSUE TITLE
Extremely large application size on Windows

### ISSUE THREAD

**Issue by innomaxx** [bloomrpc/bloomrpc#254]
Is it possible to reduce the size of the installed application? I think it's abnormal for a simple GUI gRPC client to use so much disk space.

![image](https://user-images.githubusercontent.com/40697586/94264115-cbc59400-ff3e-11ea-8a82-69c425b398c3.png)

**Comment by jackielii** [comment]
This is an Electron app, not sure we can do anything here

**Comment by innomaxx** [comment]
@jackielii, pure Electron runtime's size is 148 MB, which is relatively small

![](https://user-images.githubusercontent.com/40697586/99065043-7c4f2c00-25af-11eb-8c90-c69831795d08.jpg)

App's `node_modules` is so oversized, because BloomRPC leverages the native [`grpc`](https://www.npmjs.com/package/grpc) package (545 MB in size)

![](https://user-images.githubusercontent.com/40697586/99065279-d18b3d80-25af-11eb-90ec-ee1ace95b725.jpg)

![](https://user-images.githubusercontent.com/40697586/99065766-8cb3d680-25b0-11eb-9ffa-cdae8697f4d7.jpg)

So my question becomes pretty simple - is it possible to consider the replacement of the native oversized and deprecated [`grpc`](https://www.npmjs.com/package/grpc) package with an alternative [`grpc-js`](https://www.npmjs.com/package/@grpc/grpc-js)?

Futhermore, even `grpc` authors recommend to migrate to `grpc-js`

![](https://user-images.githubusercontent.com/40697586/99066199-37c49000-25b1-11eb-9d88-1b88992bb8bf.png)

**Comment by jackielii** [comment]
You're right. This is a reasonable request

**Comment by innomaxx** [comment]
@jackielii may you reopen this issue for a future investigation?

**Comment by innomaxx** [comment]
Hi community, any updates?
