### ISSUE TITLE
Server-side stream exception handling

### ISSUE THREAD

**Issue by jwfx** [bloomrpc/bloomrpc#256]
On version 1.4.1 it looks like the call to a server-side streaming endpoint is not properly finished when receiving an RPC exception in the response.

The spinner keeps spinning and the red stop button doesn't reset to the green start button.

![image](https://user-images.githubusercontent.com/39484381/95204316-3cdd3500-07e4-11eb-8914-92a024e41ad5.png)

Server-side implementation:
````
public override Task TestStreamingCall(TestStreamingCallRequest, IServerStreamWriter<TestStreamingCallResponse> responseStream, ServerCallContext context)
{
    throw new RpcException(new Status(StatusCode.Internal, $"Internal Error {DateTime.Now}"));
}
````

**Comment by jackielii** [comment]
does this still happens on latest?

**Comment by jwfx** [comment]
Yes, same problem on 1.5.2.

**Comment by glaubersp** [comment]
Hello, I'd like to add more info on this issue, as I'm facing the same problem.
I've build a small app to test gRPC (using micronaut + kotlin) and did some experiments.
Some observations I've done:
- When I generate a gRPC response whose header contains a message with grpc-status = 2, the connection is closed and a UKNOWN empty message is correctly shown.
**Header example:** OUTBOUND HEADERS: streamId=1 headers=GrpcHttp2OutboundHeaders[grpc-status: 2] padding=0 endStream=true
**Response Payload:**

```
{
  "error": "2 UNKNOWN: "
}

```

- When I generate a gRPC response whose header contains a grpc-status = 5, the connection is NOT closed.
**Header example:** OUTBOUND HEADERS: streamId=1 headers=GrpcHttp2OutboundHeaders[grpc-status: 5, grpc-message: Company 5 not found.] padding=0 endStream=true
**Response Payload:** 
```
{
  "error": "5 NOT_FOUND: Company 5 not found."
}
```

The code example can be found in:

- Repo: https://github.com/glaubersp/micronaut-kotlin-grpc-demo/tree/27ce2892c595d4e9534e95f9b3ec361284faea4a
- Endpoint: rpc FindAllCorporateAddressesByCompanyId(FindAllCorporateAddressesRequest) returns (stream CorporateAddress){}
- Code for the example cases can be generated editing this method: com.example.application.services.CompanyService#findAllCorporateAddressesByCompanyId

**Comment by KyloEntro** [comment]
Hi, 

I have the same issue in version 1.5.3. I have a server which raise an exception (NOT_FOUND) and Bloomrpc still waits for new answer.

**Comment by singerxt** [comment]
It's just happened to me.

Would you please resolve this issue? It is confusing for developers.

**Comment by king-leonidas1337** [comment]
The issue still exists. I have this problem with error codes other than 2
