### ISSUE TITLE
BloomRPC hangs when it gets a HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by EraYaN** [bloomrpc/bloomrpc#257]
This occurs when the server responds with a HTTP 401 to a request (services that expect some form of Authentication token for example)

**Comment by jackielii** [comment]
can you provide a bit more detail? you can use metadata to send authorization header to the server side? I'm not sure how it hangs ?

**Comment by EraYaN** [comment]
Yes, when you supply the Authorization header with metadata it works fine, but when you do not the request never finishes (in the UI that is, in the service logs you see it quickly returns a 401).

The the spinner just keeps going even though it already received a response, just not a gRPC one but an empty one.

**Comment by mehmetakbulut** [comment]
I see this same issue on `403` as well. What should happen is:
1. BloomRPC makes a call
2. Server responds with 403
3. BloomRPC shows the call failed
Instead this happens:
1. BloomRPC makes a call
2. Server responds with 403
3. BloomRPC is indefinitely waiting for the call to finish

**Comment by sbandadd** [comment]
I see the same issue with the `403` status code on version `1.4.1`.

**Comment by heggi** [comment]
1.5.3 same issue with code 401
