### ISSUE TITLE
[Windows] UNAVAILABLE: failed to connect to all addresses", even though the grpc server is online

### ISSUE THREAD

**Issue by raveltan** [bloomrpc/bloomrpc#258]
"error": "14 UNAVAILABLE: failed to connect to all addresses" 

is always returned even though the grpc is online,
the grpc client is run from wsl2 instance.

Does this has something to do with the wsl2 or is this a bug with bloomrpc?

**Comment by raveltan** [comment]
This problem seems to only exists on the windows version of the app, somehow testing on linux based machine does not result in the same random error behavior

**Comment by TimothyLks** [comment]
I am getting the same problem in Mac. Grpc is online. Any ideas on how to resolve this?

**Comment by d1820** [comment]
Same issues here as well, Any traction on this?

**Comment by emil14** [comment]
Same on linux

**Comment by makoto91** [comment]
Same issue on windows, do we have any news?

**Comment by sensei-you** [comment]
Same on Windows , version : 1.5.3
