### ISSUE TITLE
Scriptable test suite with assertions supports 

### ISSUE THREAD

**Issue by jvmlet** [bloomrpc/bloomrpc#26]
Hi
Great to see this useful stuff. 
Inspired by postman, play scenarios with assertions that could be ran from build tool as tests would be great added value.

**Comment by fenos** [comment]
Hi @jvmlet that's surely a fantastic addition for BloomRPC!
To be able to achieve this we need to first close those 2 issues:

- #6 Support Variables in Request body
- #7 Support parsing Responses with JS

This is definitely something that we want to see in the editor too! Stay tuned for future releases
