### ISSUE TITLE
[Question] Updating the environment tab does not update the subsequent RPC calls

### ISSUE THREAD

**Issue by animesh-sharama** [bloomrpc/bloomrpc#264]
Hi,

I have many saved environments such as dev, staging, productions.
Each time when I switch the environment and select an RPC for the same service I have to update the environment as well.

Is it possible to keep the environment same for all subsequent RPC calls?

**Comment by jackielii** [comment]
by subsequent do you mean after first tab opened and env selected, subsequent clicking on method to open tab should inherit the env?

**Comment by animesh-sharama** [comment]
Yes by subsequent I meant after first tab opened and env selected.
The Env for the new open tab is not as that of the one selected previously.
My configuration
```
BloomRPC version is 1.4.1
Ubuntu 20.4
```
