### ISSUE TITLE
Setting :authority headers returns Metadata key ":authority" contains illegal characters

### ISSUE THREAD

**Issue by negram** [bloomrpc/bloomrpc#281]
Hi there, 
The [issue](https://github.com/uw-labs/bloomrpc/issues/128) claimed to be resolved but it still isn't possible to use it.
Same thing happens on MacOS, bloomrpc version 1.5.2 (1.5.2.240) (and on master branch)
<img width="655" alt="Screenshot 2020-11-20 at 15 32 21" src="https://user-images.githubusercontent.com/195510/99818015-95bf1d80-2b45-11eb-833e-cd4188b324a9.png">

**Comment by palcalde** [comment]
Hi! is this still a problem? I'm unable to add the :authority header into metadata and I needed to route my requests to the GRPC server

**Comment by smnbbrv** [comment]
This is actually an issue, because it does not allow to call grpc servers behind proxies...

E.g. Gloo explicitly points to authority pseudo-header in their documentation.

https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc/

**Comment by mmohaveri** [comment]
I'm using version 1.5.2 and have the exact same issue when connecting to an API behind a proxy (gloo edge proxy)

**Comment by levischuckeats** [comment]
I also hit this issue.

**Comment by mccauli** [comment]
+1, same issue

**Comment by codingknees** [comment]
+1 same issue

**Comment by kseniacold** [comment]
This probably would not work with `metadata` at all - [based on this comment](https://github.com/grpc/grpc-node/issues/104#issuecomment-347667476): in `grpc/node`: 

> You can't directly set the :authority header because gRPC internally handles HTTP2 protocol pseudo-headers. You can modify the authority for an entire client by setting the option "grpc.default_authority" at client construction,  

Looks it should be initialized with the client creation.
