### ISSUE TITLE
BloomRPC does not work correct with import

### ISSUE THREAD

**Issue by NUnitTester** [bloomrpc/bloomrpc#291]
If it works, depends where the import is placed.
Service1 needs nothing, Service2 needs empty.
Both variants does work with the proton Compiler, but only the first one does work with BloomRPC.
The import pathes are the same in both scripts, so why should specifying an path change anything as parameter for BloomRPC?

This works:
syntax = "proto3";
option csharp_namespace = "grpcApp";
package MyTest;
**import "google/protobuf/empty.proto";**
service Service1 { ... }
service Service2 { ... }

This doesn't work for load by BloomRPC, but seems to be correct, if service1 doesn't need the import. My compiler works fine with it:
syntax = "proto3";
option csharp_namespace = "grpcApp";
package MyTest;
service Service1 { ... }
**import "google/protobuf/empty.proto";**
service Service2 { ... }

Reopend from: https://github.com/uw-labs/bloomrpc/issues/145

**Comment by jackielii** [comment]
can you be more specific? is there two files you're trying to load ? and what's the dependency?

**Comment by NUnitTester** [comment]
This should be each one file in diffrent variants.
The file contains two services with no dependencies to other files, only service2 needs something from empty.proto which is standard (and not made by myself).

`syntax = "proto3";`
`option csharp_namespace = "grpcApp";`
`package MyTest;`
`service Service1 { ... }`
`import "google/protobuf/empty.proto";`
`service Service2 { ... }`

That was the first try which works in Visual Studio but not with BloomRPC.
Than I changed the position of the import-Line and it works in BloomRPC. But as far as I now is the original version allowed and should work.

**Comment by NUnitTester** [comment]
Hello? What about fixing it?

**Comment by hxzhouh** [comment]
Hello? What about fixing it?

**Comment by vavsab** [comment]
Please update to 1.5.3 and check again. I updated grpc libraries there. If you still have the same issue I will try to reproduce and fix it.
 https://github.com/uw-labs/bloomrpc/releases/tag/1.5.3

**Comment by NUnitTester** [comment]
The problem still exists with BloomRPC 1.53.
This works. Move the bold line directly before service2, it fails. But is accepted by Proton-Compiler.

syntax = "proto3";
package MyTest;

**import "google/protobuf/empty.proto";**
service Service1 
{ 
	message SearchRequest 
	{
	  string query = 1;
	  int32 page_number = 2;
	  int32 result_per_page = 3;
	}
}
service Service2 
{ 
	message SearchRequest 
	{
	  string query = 1;
	  int32 page_number = 2;
	  int32 result_per_page = 3;
	}
	
	rpc SomeOperation (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

**Comment by NUnitTester** [comment]
Hello? What about fixing it?
So my christmas wish ...

**Comment by george-angel** [comment]
Hello @NUnitTester thanks a lot for the issue, please feel free to raise a PR to fix it.

**Comment by NUnitTester** [comment]
@vavsab [vavsab](https://github.com/vavsab)Have you reproduced it?
It is still the same.
Can you please fix it?

**Comment by vavsab** [comment]
@NUnitTester I have not reproduced your issue. Have no enough time these days. I have fixed bug for my import. Looks like your bug is a bit different.
