### ISSUE TITLE
Blank screen after application start

### ISSUE THREAD

**Issue by innomaxx** [bloomrpc/bloomrpc#297]
During the work I pressed "Refresh" app button, then it failed and screen became blank. I restarted the application - no interface control appeared + in DevConsole 3 errors (see screenshot below)

![image](https://user-images.githubusercontent.com/40697586/103460459-fe8dde00-4d1e-11eb-9bc0-5dbf286a9d01.png)

Do I need reinstall the app or this issue can be fixed in more convenient way?

**Comment by innomaxx** [comment]
Temp fix : `document.location.reload()`

**Comment by jackielii** [comment]
temporary work around is to clean the config, this issue shows where it is: #277

**Comment by jackielii** [comment]
> Temp fix : `document.location.reload()`

also control+r or cmd+r also works
