### ISSUE TITLE
Duplicate key in Metadata

### ISSUE THREAD

**Issue by washanhanzi** [bloomrpc/bloomrpc#299]
I want to have a Metadata which a key map to []string

like:
```
md := metadata.Pairs(
    "key1", "val1",
    "key1", "val1-2", // "key1" will have map value []string{"val1", "val1-2"}
    "key2", "val2",
)
```

But the metadata editor don't support duplicate keys, else I must use the "-bin" metadata.

I want to know is it possible to support duplicate keys? or what I am doing is against the document?

**Comment by jackielii** [comment]
yes, it's is reasonable to accept []string as metadata value
