### ISSUE TITLE
Error while importing protos

### ISSUE THREAD

**Issue by sdcaulley** [bloomrpc/bloomrpc#303]
OS: Debian 10
BloomRPC Version: 1.5.2

Error:  When trying to load a proto I get the error: 
```
Error while importing protos.  
no such type: <name of message>
```

The message in question is an other file being imported.  

The top of the proto file with the services looks like this:
```
syntax = "proto3";

package knova.v1;

import "models/stakato-version.proto"

service CompilerService {
     rpc ListStakatoVersion(ListStakatoVersionsRequest) returns (ListStakotoVersionsResponse) {}
```
And the imported file looks like:
```
syntax = "proto3";

package knova.v1;
message ListStakatoVersionsRequest { ... }
```
Any ideas on why BloomRPC cannot load the proto?

**Comment by pokatos** [comment]
@sdcaulley Have you set ` Import Paths`?
<img width="1324" alt="Screenshot 2021-02-17 at 17 01 51" src="https://user-images.githubusercontent.com/48278035/108223045-0cb68300-7142-11eb-8d2d-66b749837281.png">
