### ISSUE TITLE
Wrap long lines + hotkeys

### ISSUE THREAD

**Issue by fabsenet** [bloomrpc/bloomrpc#305]
Hi,

I have to have regularly very long strings in my GRPC requests. I would love to have a way to enable wrapping of long lines to have a better overview over my request.

Also it would be great to have a keyboard shortcut for request sending. I would like to have CTRL+Enter (like sending mail in outlook or gmail).

Thanks for bloomrpc, it is exactly what I need!

**Comment by Amritkrlama** [comment]
Hi,

Did you get the way to wrap the text?
