### ISSUE TITLE
When I close all of the tabs, I find that there are tabs left

### ISSUE THREAD

**Issue by Jacksliwen** [bloomrpc/bloomrpc#307]
![屏幕截图(14)](https://user-images.githubusercontent.com/48372041/106136466-5136aa80-61a4-11eb-8f0e-80d9b26fef51.png)

**Comment by Mreddi1** [comment]
I have the same problem. I can't close those tabs.
MacOS 11.1 | BloomRPC 1.5.2 (1.5.2.240)

**Comment by alhamsya** [comment]
i have same problem

**Comment by Porcupine96** [comment]
Same thing on Arch Linux | BloomRPC 1.5.2.

**Comment by Mreddi1** [comment]
@Porcupine96 @Jacksliwen https://github.com/uw-labs/bloomrpc/issues/277
