### ISSUE TITLE
Feature Request: Adjust width of import proto panel

### ISSUE THREAD

**Issue by gmkohler** [bloomrpc/bloomrpc#322]
For RPCs with similar but long names it becomes difficult to know at a glance which RPC I'm opening up in the GUI.  In an IDE for example I can adjust the width of the project view sidebar.  It would be useful to have this feature on this GUI

![Screen Shot 2021-03-19 at 13 55 10](https://user-images.githubusercontent.com/12285859/111841313-03444600-88bb-11eb-97d1-97a7c319a841.png)

(Using macOS BloomRPC Version 1.5.2 (1.5.2.240))

**Comment by allan2** [comment]
I agree, this is something that is good to have. PRs are welcome!

**Comment by gmkohler** [comment]
@allan2 Any pointers on what parts of the code to look at?  I am somewhat familiar with TypeScript but pretty unfamiliar with UI programming.
