### ISSUE TITLE
Feature request: FileDescriptorSet (Protoset) support

### ISSUE THREAD

**Issue by tahmed-wish** [bloomrpc/bloomrpc#324]
The protoc compiler allows options to create a file descriptor set via options `--descriptor_set_out=FILE`

This can be used to compile all protobuf files into a single protoset file containing information about all proto files. Often times, my proto dependencies are across various different projects and its a little too cumbersome to specify the proto files one-by-one. This way, I can generate a protoset file and import one file instead. I do this when using grpcurl, which allows you to specify protoset via option `-protoset`. I was wondering if adding this support to bloomrpc might be a good feature?

**Comment by foolishnoob** [comment]
Maybe u can use [grpcui](https://github.com/fullstorydev/grpcui) instead. I used bloomrpc before , but there r some problems trouble me ,such as proto-gen-validate code could not be parsed, third party proto files import could not be parsed and so on.
