### ISSUE TITLE
google.protobuf.Timestamp error

### ISSUE THREAD

**Issue by shashank-sachan** [bloomrpc/bloomrpc#331]
Hi,

When I'm trying to import an proto file in bloomrpc then I'm getting following error:
`no such Type or Enum 'google.protobuf.Timestamp' in Type .message.Message`

As far as I know this is supported by default in bloomrpc but not sure why this error is coming. Do we need to import it explicitly?

**Comment by gsmeets** [comment]
I just ran into this issue as well, turns out the case naming of the file names is case sensitive. Maybe this is the issue for you as well.

So use this:

```
import "google/protobuf/timestamp.proto";
```

instead of:

```
import "google/protobuf/Timestamp.proto";
```

**Comment by neomichi** [comment]
Thanks, it works.

**Comment by momink** [comment]
Thanks that worked.  The code in VS2022 compiled with no errors with the capital T Timestamp, but failed to load in bloomrpc. Changing it to all lower case worked.
