### ISSUE TITLE
Code cache gets stale and has to be blown away.

### ISSUE THREAD

**Issue by DavidSwiftHadoop** [bloomrpc/bloomrpc#336]
We've found on Windows and Mac in the last week that the code cache can get out of date and then has to be deleted for things to work properly. On Windows, it's here: bloom-rpc-client\Code Cache. We're having a difficult time finding the corresponding directory on Mac, but it might be even nicer if there were a button to blow away this cache. In the meantime, can someone comment as to where we could find it on a Mac? Thanks!

**Comment by jitendratheta2** [comment]
Yes thats correct, modification in API contract are not read properly.. looks lie there is some kind of cache which still reads from older contract
