### ISSUE TITLE
Unable to use the newly added fields in proto files using bloomrpc

### ISSUE THREAD

**Issue by jitendratheta2** [bloomrpc/bloomrpc#354]
Say the proto had message as below
`message EvaluateRequest {
    RequestContext request_ctx = 1;
    RequestInfo request_info = 2;
}`

It was imported and used in bloomRPC. After which it has been updated as below

`message EvaluateRequest {
    RequestContext request_ctx = 1;
    RequestInfo request_info = 2;
    UserInfo user_info = 3;
}`

proto removed and reimported again in bloomRPC. Now bloom RPC doesn't recognise the third field "user_info" at all.
It only passes the older two fields in the request

Similar issue is reported earlier
https://github.com/uw-labs/bloomrpc/issues/188

**Comment by jitendratheta2** [comment]
one more related issue found https://github.com/uw-labs/bloomrpc/issues/336

**Comment by hacetin** [comment]
Are there any updates on this? I also have the same issue on macOS. The app does not reflect the changes in the protocol buffers. Uninstalling and installing again did not work. Also, removing the `/Users/user/Library/ApplicationSupport/bloom-rpc-client` directory did not work for me (See https://github.com/uw-labs/bloomrpc/issues/336).

**Comment by hacetin** [comment]
Wrong alarm, there was a path confusion in my case. Somehow the problem is fixed but I am not sure what fixed the problem. I removed whatever I could find about Bloom RPC and uninstalled it. After reinstalling it, the problem was fixed.

**Comment by jitendratheta2** [comment]
Got the resolution for this.. removing the local cache solve it..

For mac delete the application support data for bloom-rpc

`rm -rf ~/Library/Application\ Support/bloom-rpc-client`
