### ISSUE TITLE
Imports not working 

### ISSUE THREAD

**Issue by PradeepLoganathan** [bloomrpc/bloomrpc#357]
This maybe a duplicate of https://github.com/uw-labs/bloomrpc/issues/102 but still want to raise it as the solution to 102 does not fix a similar problem that I have. I have two proto files in my Protos folder.

The first file with the interface definition
```
syntax = "proto3";

option csharp_namespace = "GrpcService1.Protos";

import "Protos/ReportingStatus.proto";
import "google/protobuf/timestamp.proto";


package GrpcService1;

service MetricReportingService {
	rpc ReportMetricData(MetricMessage) returns (StatusMessage);
}
message MetricMessage {
	int32 id = 1;
	int32 value = 2;
	//google.protobuf.TimeStamp last_updated = 3;
}

message StatusMessage {
	ReportingStatus status = 1;
}
```

The second file defining ReportingStatus is below

```
syntax = "proto3";

package GrpcService1;
option csharp_namespace = "GrpcService1.Protos";

enum ReportingStatus {
	INVALID = 0;
	SUCCESS = 1;
	FAILURE = 2;
}
```

In the tool I have set the import path to the folder where these proto files exist. When i try to load the first proto file i get the below error.

Error while importing protos
no such Type or Enum 'ReportingStatus' in Type .GrpcService1.StatusMessage

Not sure how to resolve the issue.

**Comment by alexisvisco** [comment]
Same problem here, and since bloom rpc does not support reflection, it is unusable. Was great to use for non-production use.

**Comment by yiippee** [comment]
Same problem here

**Comment by PPY-hei** [comment]
In order to resolve this problem, you can append your project root to Path where on the bloom rpc left side。For example /User/xx/xxProject

**Comment by PPY-hei** [comment]
> Same problem here

In order to resolve this problem, you can append your project root to Path where on the bloom rpc left side。For example /User/xx/xxProject

**Comment by PPY-hei** [comment]
> This maybe a duplicate of #102 but still want to raise it as the solution to 102 does not fix a similar problem that I have. I have two proto files in my Protos folder.
> 
> The first file with the interface definition
> 
> ```
> syntax = "proto3";
> 
> option csharp_namespace = "GrpcService1.Protos";
> 
> import "Protos/ReportingStatus.proto";
> import "google/protobuf/timestamp.proto";
> 
> 
> package GrpcService1;
> 
> service MetricReportingService {
> 	rpc ReportMetricData(MetricMessage) returns (StatusMessage);
> }
> message MetricMessage {
> 	int32 id = 1;
> 	int32 value = 2;
> 	//google.protobuf.TimeStamp last_updated = 3;
> }
> 
> message StatusMessage {
> 	ReportingStatus status = 1;
> }
> ```
> 
> The second file defining ReportingStatus is below
> 
> ```
> syntax = "proto3";
> 
> package GrpcService1;
> option csharp_namespace = "GrpcService1.Protos";
> 
> enum ReportingStatus {
> 	INVALID = 0;
> 	SUCCESS = 1;
> 	FAILURE = 2;
> }
> ```
> 
> In the tool I have set the import path to the folder where these proto files exist. When i try to load the first proto file i get the below error.
> 
> Error while importing protos
> no such Type or Enum 'ReportingStatus' in Type .GrpcService1.StatusMessage
> 
> Not sure how to resolve the issue.

In order to resolve this problem, you can append your project root to Path where on the bloom rpc left side。For example /User/xx/xxProject

**Comment by rustyx** [comment]
Specify correct **import path(s)** before importing `.proto` files into BloomRPC:

![BloomRPC import path](https://user-images.githubusercontent.com/1296899/142908642-d705b8a1-6f2d-42e1-bdae-c54628baa075.png)

In your case, the path that contains the `Protos` folder so that `<import path>/Protos/ReportingStatus.proto` can be found.
