### ISSUE TITLE
[Bug] ignores Cancelled status

### ISSUE THREAD

**Issue by ivan-iljin** [bloomrpc/bloomrpc#360]
I can confirm that it's displaying correctly responses with the following Status Codes:
- Invalid Argument
- Internal
- Aborted
- Resource Exhausted
- Deadline Exceeded

But it seems to simply ignore Cancelled response status. Both with one-shot request and with streaming request. Simply doesn't react to such response, remains in waiting status forever.

UPD: all statuses are displayed correctly but Cancelled isn't.

Btw awesome tool, using it happily! Much love!

**Comment by allan2** [comment]
Can you provide more information? OS, version, proto file, method call

**Comment by Thothore** [comment]
Hello, I have currently the same issue, on Windows 10, bloomrpc is in version 1.5.3. I cannot provide the proto but basically it is something like that : 
```
rpc MethodName (Request) returns (Response);
message Request {
int32 param = 1;
}
message Response {
string doesNotMatter = 1;
}
```
And the server, will take some time and at some point will throw an RpcException(new Status(StatusCode.Cancelled, "MethodName cancelled."))), which cannot be seen on bloomrpc. The method is shown as still waiting while the same test on postman returns the status cancelled.
The language is dotnet6.

**Comment by ivan-iljin** [comment]
Sorry about the delay.
https://github.com/ivan-iljin/test-grpc-return-statuses

Now I can tell that all the statuses get displayed, only Cancelled just hangs forever.

**Comment by ivan-iljin** [comment]
Looking at the packets via Wireshark, I can see that in case of Cancelled, BloomRPC does not end the connection.
Here is how a session with OK returned looks:
![obraz](https://user-images.githubusercontent.com/77777672/156225756-e9ad6ba1-a596-40e4-a6d2-f2816564c866.png)
It is visible that right after the packet with status code 0(OK) (highlighted, contents at the bottom), the client sends ACK, and then FIN+ACK, meaning it wants to close the connection.

And here is how a session with Cancelled returned looks:
![obraz](https://user-images.githubusercontent.com/77777672/156226268-2103de8f-d73a-4ada-9c74-f6f6c61bc34d.png)
Here we can see the same package with the status 1(Cancelled). The client sends ACK in response, confirming the receipt. But does not try to finish the connection.

In GRPC docs here
https://grpc.github.io/grpc/core/md_doc_statuscodes.html
We can see that Cancelled can be thrown either by Client or by Server (see the table at the bottom of the linked page).
I believe that means that Client must also be able to finish the connection in such case, as the client is not always the initiator of the Cancelling.
I might be mistaken, and the client might not need to end the connection in such case.
Some GRPC evangelist's help would be greatly appreciated.

However, BloomRPC should at least display the Cancelled status. Even if not end the connection until Stop is clicked.
