### ISSUE TITLE
[FeatureRequest]Add saving request and load it next time directly

### ISSUE THREAD

**Issue by youyuxiansen** [bloomrpc/bloomrpc#363]
Hi, developers of bloomrpc.This tool means a lot to me! Thank you.
Let me explain it. I have set a request that one of the key-value including bytes of image and is very long. I want to save it and load it next time directly.
![image](https://user-images.githubusercontent.com/35478566/123025554-58897980-d40d-11eb-9b70-f8ea75c7d174.png)
![image](https://user-images.githubusercontent.com/35478566/123025583-6212e180-d40d-11eb-986f-58e7dcc93441.png)

**Comment by ivan-iljin** [comment]
If you don't close the tab when closing BloomRPC, it does save the request data. :)
If you want an interface for storing requests explicitly for loading (i'd love that, too), then i think that's a significant new feature, not a humble enhancement. ;)

**Comment by youyuxiansen** [comment]
If you want an interface for storing requests explicitly for loading

**Comment by youyuxiansen** [comment]
> If you don't close the tab when closing BloomRPC, it does save the request data. On next launch, it will be available for re-sending. :)
> If you want an interface for storing requests explicitly for loading (i'd love that, too), then i think that's a significant new feature, not a humble enhancement. ;)
“If you want an interface for storing requests explicitly for loading”
Yes, that's what I want.
