### ISSUE TITLE
Feature - Add splitter to expand the window

### ISSUE THREAD

**Issue by arkanmgerges** [bloomrpc/bloomrpc#365]
Hi,
Thank you for making this app. If it is possible to make the area where the services are, expandable, because I have long service names, right now I need to use the horizontal scroll bar to see find the service, it would be nice if I can expand the area:

![image](https://user-images.githubusercontent.com/7836805/123380835-9bc42380-d598-11eb-9348-3753662bf792.png)

Thank you,
Arkan

**Comment by gmkohler** [comment]
Seconded here https://github.com/uw-labs/bloomrpc/issues/322

**Comment by allan2** [comment]
Closed as duplicate of #322
