### ISSUE TITLE
What is the situation？

### ISSUE THREAD

**Issue by boteman0206** [bloomrpc/bloomrpc#367]
When I run this software, the error is:

Error constructing the request
e[this.protoInfo.methodName] is not a function

**Comment by allan2** [comment]
Can you provide more information on your setup, including OS, BloomRPC version, proto file, and call parameters?

**Comment by anderewrey** [comment]
Got the same problem, but I can give more details...

Windows 10
BloomRPC 1.5.3
Notepad++ v8.3.3


With a file, hosted in my Linux VM and accessed/edited through Samba...
- Executing the existing requests work without problem.
- Duplicating an existing request (by simply adding '2' at the end of its name), I get the same problem as mentioned.

With the same working .proto file (UNIX LF-ending, UTF-8) but hosted locally in Windows, there is no problem at all.

Now, the most funny thing... Now I get it working, if I reuse my file hosted in my Linux VM, it works.
