### ISSUE TITLE
optional fields

### ISSUE THREAD

**Issue by AmirrezaKN** [bloomrpc/bloomrpc#369]
hey there
i have a proto3 file with this message

```Protocol Buffer
message PermaRequest {
    enum Server {
        unknown_server = 0;
        local          = 1;
        main           = 2;
    }

    int64 file_id          = 1;
    optional Server server = 2;
}
```
and the request i want to send with bloomrpc is this
```json
{
  "file_id": 20,
  "server": 0
}
```

but i get this error

> Error constructing the request
> keys that don't end with '-bin' must have String values

what am i doing wrong here?

**Comment by Kurru** [comment]
Proto3 doesnt use the `optional` keyword anymore. You can just omit that? Perhaps thats the problem?
