### ISSUE TITLE
Response metadata

### ISSUE THREAD

**Issue by optiman** [bloomrpc/bloomrpc#37]
It would be nice to see not only response body but also response metadata.
It could be useful if server provides validation errors in gRPC status details.

**Comment by fenos** [comment]
Great request!
I'll see what i can do about it

**Comment by mavrick** [comment]
this would be most helpful in debugging connection issues with grpc through proxies/cloudflare etc.

**Comment by chrisenytc** [comment]
@fenos Any updates on this feature? I would be glad to contribute to make this possible.

**Comment by moh-abk** [comment]
any ETA on this?

**Comment by kusdavletov** [comment]
Still no updates? Would be great to see this feature :)

**Comment by sirajmansour** [comment]
Great feature to have

**Comment by pantuchy** [comment]
Waiting for this feature, will be very useful.
Thank you.

**Comment by NicolasCaous** [comment]
I need this feature :'(

**Comment by nisart007** [comment]
A feature must required

**Comment by tahmed-wish** [comment]
Any update on this? Would be a very useful feature!
