### ISSUE TITLE
Installation hangs on Win10

### ISSUE THREAD

**Issue by boldt** [bloomrpc/bloomrpc#370]
On Win10, the installation hangs:

![grafik](https://user-images.githubusercontent.com/750793/125632633-95c59557-e32e-42df-98a3-4535ccaff5ac.png)

What can be the issue?
How can I debug it?

**Comment by allan2** [comment]
@boldt Hi, we went through a change in maintainers recently. If you are still having an issue, please post it here and we will try to help!

**Comment by boldt** [comment]
Hey @allan2. I still have exalty the same issue. I cannot install 1.5.3
