### ISSUE TITLE
when proto parse failed, bloomRPC is blank

### ISSUE THREAD

**Issue by linuxxiaoyu** [bloomrpc/bloomrpc#371]
* env
  os: macOS Big Sur 11.4 (20F71)
  BloomRPC: 1.5.2.240

When proto file parse failed, BloomRPC window is blank, then restart BloomRPC,  the list of files on the left becomes empty. Looks like it's been reset.

**Comment by Metalscreame** [comment]
Faced this two time as well

**Comment by kelvie-pstg** [comment]
This is especially bad when using server reflection -- when the server goes down, the screen stays blank and can't be fixed until you bring the server back up, even after restarts
