### ISSUE TITLE
Update electron, because of Let's Encrypt DST Root CA X3 certificate expiration 

### ISSUE THREAD

**Issue by giovanni-annunzio** [bloomrpc/bloomrpc#387]
Hello all,

Recently the IdenTrust root certificate expired in Electron. Are you planning to update Electron?

BR
G

**Comment by mbn18** [comment]
Second that. `BloomRPC` can not work with GRPC that use `Lets Encrypt`

**Comment by george-angel** [comment]
https://github.com/bloomrpc/bloomrpc/issues/398
