### ISSUE TITLE
Broken on Fedora 35

### ISSUE THREAD

**Issue by GTB3NW** [bloomrpc/bloomrpc#394]
It's not possible to launch on fedora 35 using the appimage without the following flag: `--disable-features=VizDisplayCompositor`

The following error is display:

> The display compositor is frequently crashing

**Comment by Jubblin** [comment]
Same issue experienced on Ubuntu 22.04

bloomrpc 
[1096302:0807/162943.806903:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
