### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by george-angel** [bloomrpc/bloomrpc#398]
Hello!

The original author of the project has left the company and currently we don't have people internally who actively use / are willing to support BloomRPC.

Would anyone be interested in becoming a maintainer?

In case there is sufficient interest and we have volunteers - we will create a new org, move the project there and admin the volunteers.

If not, I'm afraid we'll have to declare project "not maintained" and archive.

Thanks all.

**Comment by allan2** [comment]
I'm interested. I'd hate to see the project unmaintained.

**Comment by gunturaf** [comment]
Hi there, I'm interested, we at Stockbit.com use bloomrpc heavily on our day to day workflow.

**Comment by allan2** [comment]
I created a Discord
https://discord.gg/r7n6sxUu

**Comment by mrjosh** [comment]
Me and my team uses this great platform and we dont want to see this project unmaintained.
I would love to maintain this project

**Comment by dmop** [comment]
I use this project on a daily basis in my company, I would love to help to be a maintainer also.

**Comment by UnsolvedCypher** [comment]
@allan2 could you please create an updated invite link? The one you posted seems to have expired

**Comment by allan2** [comment]
@UnsolvedCypher  This one won't expire

Discord link for BloomRPC: https://discord.gg/n5k44hrAfM

**Comment by btlk** [comment]
Hi, could somebody please update this thread regarding the future of this project?  
Were the new maintainers found?

**Comment by allan2** [comment]
Yes, three new maintainers were found including myself.

We are still looking for more maintainers. @btlk interested?

**Comment by george-angel** [comment]
Hello! I have since handed over org admin to a few individuals who volunteered in this thread and then left the org.

I now have more people volunteering as maintainers, can one of the existing org admins please re-instate me so I can add these people please?

There is also https://github.com/uw-labs/bloomrpc-mock - that needs to be migrated to this org. Thanks!
