### ISSUE TITLE
installation is broken

### ISSUE THREAD

**Issue by artemkozlenkov** [bloomrpc/bloomrpc#400]
- installation from source described here https://github.com/bloomrpc/bloomrpc#to-build-from-source is broken with multiple errors related to dependencies. 
- installation from brew is broken.

switching to other branches doesn't help either. 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by allan2** [comment]
Could you provide the error output?

**Comment by artemkozlenkov** [comment]
the installation from source works for me again
