### ISSUE TITLE
When will be released version with apple silicon support?

### ISSUE THREAD

**Issue by baza04** [bloomrpc/bloomrpc#405]

**Comment by dpangier** [comment]
The M1 has been in production Macs for over a year now. I was surprised how few apps are Intel only still.  This, sadly, is one of them.

**Comment by george-angel** [comment]
Hello @dpangier we will gladly accept a PR from you.

https://github.com/bloomrpc/bloomrpc/issues/398

**Comment by allan2** [comment]
Duplicate of #383
