### ISSUE TITLE
Rebuild with Newer Root Certificates - Unable to Connect to All Addresses Error

### ISSUE THREAD

**Issue by steve-gray** [bloomrpc/bloomrpc#410]
Hey folks,

There's another issue related to this the reporter has closed, but #402 is becoming increasingly a problem now. In the nearly 7 months since the last build, many root CA's have updated their certificate chain. Would it be possible to get a rebuild/updated version pushed and updated on Brew please? No code changes in principal, just an updated electron bundle/certificates.

The specific problem is that the bundle that shipped with the last build doesn't have trust for ISRG Root X1 from LetsEncrypt, which most recently issued certificates are backed by. I spent the best part of a few days debugging random ingress issues and firewall stuff, I stumbled onto the issue.

**Comment by Metalscreame** [comment]
+1, due to this it's impossible for me to use this beatufill software

**Comment by nlflint** [comment]
I had the same issue, can't use this tool with our GRPC services on a k8s cluster with LetsEncrypt signed ingresses. There is a workaround: import the Let's Encrypt CA into BloomRPC yourself.

1. Open a Let's Encrypted secured website in your browser, click the padlock, and go thru the UI to export a Let's Encrypt CA pem file.
2. Or find another way to get their CA into a PEM file format.
3. In BloomRPC, click the TLS control and add the root cert
  ![image](https://user-images.githubusercontent.com/1383530/154763632-49663653-c5ce-49cc-9b8a-1c7d5b70d996.png)
4. Select your new cert via the radio button and click Done
5. Should work now.

**Comment by Metalscreame** [comment]
This solution worked for me. Sadly is a temporal due to cert will expire:(
