### ISSUE TITLE
Error constructing the request e[this.protoInfo.methodName] is not a function

### ISSUE THREAD

**Issue by AsmaRahimAliJafri** [bloomrpc/bloomrpc#411]
I have bloomRPC version 1.5.3 - for any new proto file that is imported. It gives the above issue. I have cross-checked by running calling the same rpc on another computer, which works just fine. Please fix this ASAP

**Comment by AsmaRahimAliJafri** [comment]
@allan2 @fenos @jackielii @vavsab @EricSmekens

**Comment by mklef121** [comment]
I have this same issue currently on windows 10.

**Comment by akhilapoliset** [comment]
Was this issue fixed?

**Comment by Fizpok** [comment]
e[this.protoInfo.methodName] is not a function - still relevant!

**Comment by rahulmenswig** [comment]
what is the fix for this issue ?
Can someone please update

**Comment by allan2** [comment]
Could you post your `.proto` file and a screenshot of the error?

**Comment by AlexanderVolkovTCS** [comment]
>Could you post your .proto file and a screenshot of the error?

for example, add both [instruments.proto](https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/instruments.proto) and [common.proto](https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/common.proto) files 
from 
https://github.com/Tinkoff/investAPI/tree/main/src/docs/contracts

I have error "e[this.protoInfo.methodName] is not a function" with Options() or OptionBy() methods.
Windows 10
