### ISSUE TITLE
would be nice if the app removes whitespaces from the path. 

### ISSUE THREAD

**Issue by creadicted** [bloomrpc/bloomrpc#414]
Hello! 
It would be nice if the app would remove whitespaces from the path.
Spot the difference:
![grafik](https://user-images.githubusercontent.com/1899013/149120420-392a4f1d-5ccb-428c-8455-8f97d2e7a553.png)

**Comment by allan2** [comment]
What is the current behaviour?

**Comment by Kurru** [comment]
Likely fails to connect due to leading/trailing whitespace?
