### ISSUE TITLE
Cannot read property indexOf in version 1.5.3

### ISSUE THREAD

**Issue by bbemis017** [bloomrpc/bloomrpc#418]
Hi I ran into an issue while upgrading from BloomRPC 1.5.2 to 1.5.3. When I try to re-import my proto file I get this error:
![image](https://user-images.githubusercontent.com/8581332/151593302-515204b9-ca89-42a4-92bd-1c9647e0a0fc.png)
Is this expected?

I do have to provide import paths because we don't define everything in a single proto file. So I have a directory structure like this:

```
proto/
    project_name/v1/
           service.proto
           other.proto
    VERSION.txt
```

I've tried setting the import path to be the proto directory which is what worked on version 1.5.2, but now on version 1.5.3 I get the error I posted above. I also can't set the import path to be proto/project_name/v1 because we want to include v1 in our package name, so we get no such type errors if we do that.

so it kind of seems like 1.5.3 may not support importing protos that have leading package names

**Comment by alee792** [comment]
I also have a similar issue where an extension breaks the import: 
```
extend google.protobuf.MethodOptions {
		optional string foo = 1000;
};
```

**Comment by alee792** [comment]
It looks like `optional` is what the parser takes issue with.

**Comment by matthewkosloski-asi** [comment]
Try downgrading to [1.5.2](https://github.com/bloomrpc/bloomrpc/releases/tag/1.5.2)
