### ISSUE TITLE
1.5.3版本不支持enum类型的protoc-gen-validate验证

### ISSUE THREAD

**Issue by zhangya4548** [bloomrpc/bloomrpc#423]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/8876518/156971586-5391d350-115e-472a-ae88-7e00ce3ca074.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/8876518/156971629-ad366b8a-c00a-4789-b280-c00df26e734b.png">

**Comment by vominhtrius** [comment]
I have the same issue.

**Comment by int3cd** [comment]
https://github.com/bloomrpc/bloomrpc/issues/389
