### ISSUE TITLE
New release process

### ISSUE THREAD

**Issue by jackielii** [bloomrpc/bloomrpc#432]
This was previous release process I got from @fenos :

- create the release in Draft mode
- PR the update the version in the package.json 
- Let CI finish - it will upload the artifacts
- Then Publish the release.

However, I think after transferring the repo to the new org, it's not working anymore, I don't have the original CI access.

So we need to come up with a new one, most likely using github actions

**Comment by FyiurAmron** [comment]
any update on this or is building manually the only option?
