### ISSUE TITLE
Is there any command line version of this tool?

### ISSUE THREAD

**Issue by arfan** [bloomrpc/bloomrpc#433]
I was just wondering if there Is a command line version of bloomrpc?

**Comment by ivan-iljin** [comment]
The idea of BloomRPC is to provide a GUI tool.
There are quite a number of implementations of CLI GRPC tools.
Here is the official one
https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md

**Comment by arfan** [comment]
is it possible to generate the command line from bloomrpc to those tools?
