### ISSUE TITLE
Add support import/export grcurl

### ISSUE THREAD

**Issue by fleytman** [bloomrpc/bloomrpc#447]
This very important feature, for fast coomunicete in develop team. Now this feature has wombat https://github.com/rogchap/wombat/pull/51, but with bug https://github.com/rogchap/wombat/issues/50#issuecomment-1236460826

**Comment by allan2** [comment]
BloomRPC should be server-agnostic. What is the feature you are looking for?

**Comment by fleytman** [comment]
I don't see how requesting an import/export function like grpcurl contradicts the concept of server-agnostic. This feature is similar to the one in postman for curl. It's usually much easier to send a console line to someone on the team to reproduce some problem than to explain how to configure something in a gui tool.

**Comment by allan2** [comment]
I understand now... that sounds like a good idea to me!
