### ISSUE TITLE
"error": "14 UNAVAILABLE: failed to connect to all addresses"

### ISSUE THREAD

**Issue by 1wukai** [bloomrpc/bloomrpc#451]
![image](https://user-images.githubusercontent.com/45681614/200495195-94eb087d-9f0e-446e-a218-aa4c4712a2bd.png)

`**Can I set - security direct access like grpcurl**`

![image](https://user-images.githubusercontent.com/45681614/200495416-3740d8d3-193c-4009-97e2-57658b6dea89.png)

**Comment by mbn18** [comment]
Same for me when trying to dispatch to a TLS endpoint.
`grpcurl` works
