### ISSUE TITLE
[Feature Request] Save data of request in the collection

### ISSUE THREAD

**Issue by paulooosrj** [bloomrpc/bloomrpc#92]
In the application not support save data of a request in a collection for to be reusable. This help all peoples than using the **BloomGRPC**

**Comment by fenos** [comment]
hi, @paulooosrj Yes! this is a lovely request and we are keen to implement it in the editor.

I can't give you any timeline for this but surely is something we'd love to see as well!

**Comment by paulooosrj** [comment]
Thank for accept my feature, request this is very good. :)

**Comment by nammn** [comment]
👋  @fenos has there been any progress/thoughts on this issue? Bloomrpc is working great for me so far, only missing feature I see is the `collection` similar to `postman`. If you have some nice pointers I might be able to lend a helping hand 📓 .
