### ISSUE TITLE
dark mode support

### ISSUE THREAD

**Issue by leaxoy** [bloomrpc/bloomrpc#94]

**Comment by fenos** [comment]
@leaxoy interesting idea!

I will eventually get there but we have more important feature to implement at the moment.
But surely it will be a great addition

**Comment by IgorHalfeld** [comment]
Wow, It would be nice!

**Comment by yuraxdrumz** [comment]
I am working on a `styled-components` based dynamic dark mode. Should be ready in 2-3 days

**Comment by yuraxdrumz** [comment]
Okay, so I have an initial working version with `styled-components`. I leveraged the `ThemeProvider`, which allows dynamic theme support. Another thing is that it allows reusability, very easy to extend styles and removes the need for inline styles + scss files. I will polish the code and pick a color pallette that suits a bit better over the next couple of days and then open a PR.
Thanks.
![dark2](https://user-images.githubusercontent.com/17418978/74596780-a2fe2780-505c-11ea-83e0-d1370771bea7.png)
![white](https://user-images.githubusercontent.com/17418978/74596786-ae515300-505c-11ea-9c44-8f8171c93290.png)
![whte-tls](https://user-images.githubusercontent.com/17418978/74596809-ec4e7700-505c-11ea-9884-ffd9b601a849.png)
![dark-tls](https://user-images.githubusercontent.com/17418978/74596810-f07a9480-505c-11ea-8151-d8021c866188.png)

**Comment by wlacruzpy** [comment]
Ahh I really need this feature! is there anybody working on it?
