### ISSUE TITLE
Illegal value '['

### ISSUE THREAD

**Issue by lopezator** [bloomrpc/bloomrpc#96]
We have defined some extra properties: 

```
// API tags applied at the message level
extend google.protobuf.FieldOptions {
    mycompany.api.ResourceName resource_name = 818181;
}
```

And make use of them like this:

```
message MyMessage {
    string name = 1 [
        (mycompany.api.resource_name) = {
            any: [
                "some/*/format/*",
                "other/*/format/*"
            ]
        }
    ];
}
```

Given these protos, when importing them, BloomRPC throws this error:

```
illegal value '[' (/Users/myuser/go/src/gitlab.mycompany.com/my-apis/spec/mycompany/myproject/myfolder/v1/myproto.proto, line 100)
```

The only workaround I found is just dropping that part.

```
message MyMessage {
    string name = 1;
}
```

**Comment by fenos** [comment]
@lopezator Hi, 
I will have a look at this, but it sounds like some sort of limitation of `protobuf.js` parser.

I'll let you know once i've got some more information

**Comment by lopezator** [comment]
If it were the case, maybe we should move the issue there.

Thanks @fenos!

**Comment by glerchundi** [comment]
@fenos bitten by the same, I tried to create my own dev workspace in order to see if the problem comes from protobuf-js but the steps on the CONTRIBUTING part of the README didn't work for me. Did you have time to look at this or anything I can do to push this forward?

**Comment by fenos** [comment]
@glerchundi i haven't look this yet, i'm fairy busy at the moment, but i'll get to this asap

**Comment by glerchundi** [comment]
No rush, thanks for keeping us updated!

**Comment by nickrobinson** [comment]
Running into the same issue with Version 1.4.1 (1.4.1.145)

**Comment by fenos** [comment]
Unfortunately this is a limitation of protobufjs parser, you can read more information here.

https://github.com/uw-labs/bloomrpc/issues/115

I'll try to make it work in a different way in future releases if the PR doesn't get merged

**Comment by dharmjit** [comment]
Hi, facing the same issue. Any update.

**Comment by mkfsn** [comment]
Hi folks, it seems like https://github.com/protobufjs/protobuf.js/pull/1256 has been merged and released, do you have any update about this issue?

**Comment by mcopjan** [comment]
any update on this please? ^^

**Comment by mcopjan** [comment]
@fenos ?

**Comment by wolfogre** [comment]
Same problem when using [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate), any update?
```
DomainKind kind = 11 [(validate.rules).enum = {in: [1,2,3]}];
```
![image](https://user-images.githubusercontent.com/9418365/119790419-7fd05200-bf06-11eb-8180-8ee9787f150c.png)

**Comment by monotone** [comment]
@fenos 
facing the same problem

**Comment by CyborgMaster** [comment]
Now that protobufjs/protobuf.js#1256 has been merged, it feels like the only change should be updating the package.json file.  I tried to do it myself and could figure out how to get the dev environment up and running.  Anyone else want to take a crack on it?  Hopefully a one line change.

**Comment by monotone** [comment]
it already so long for this issue.

**Comment by self-tuts** [comment]
Any update of this

**Comment by kos-maverik** [comment]
Facing the same problem, is there any update on this?

**Comment by darewreck54** [comment]
Any updates on this?

**Comment by akalittle** [comment]
Any updates on this?

**Comment by wuqinqiang** [comment]
Any updates on this?

facing the same problem.😂

**Comment by M-Kepler** [comment]
Any updates on this?

facing the same problem too.
